### ISSUE TITLE
Error Handling

### ISSUE THREAD

**Issue by henrywuhu** [matthewgilbert/pdblp#33]
Hey. 

I am doing a program to fetch data from bloomberg.  I read a csv file that contains tickers. If a ticker is invalid, how can i do the error handling. 

For example USBX@ is not a valid security my code is the following:

```python
con = pdblp.BCon(debug=False, port=8194)
con.start()
try:
    x = con.bdh('USBX@ Curncy', 'PX_BID', '20180509','20180509')
except ValueError:
    print("ERROR")
```
for example if I run it on Pycharm I get the following string of exceptions. In this I can check that there is an invalid security, but how can I get the subcategory error immediately  from try except using ValueError or NameError
```python
Traceback (most recent call last):
  File "C:/Users/hwuhu/PycharmProjects/PRUEBA/PRUEBBA.py", line 22, in <module>
    x = con.bdh('USBX@ Curncy', 'PX_BID', '20180509','20180509')
  File "c:\users\hwuhu\pdblp\pdblp\pdblp.py", line 165, in bdh
    elms, ovrds)
  File "c:\users\hwuhu\pdblp\pdblp\pdblp.py", line 203, in _bdh_list
    raise Exception(msg)
Exception: HistoricalDataResponse = {
    securityData = {
        security = "USBX@ Curncy"
        eidData[] = {
        }
        sequenceNumber = 0
        securityError = {
            source = "4013::bbdbh5"
            code = 15
            category = "BAD_SEC"
            message = "Unknown/Invalid securityInvalid Security [nid:4013] "
            subcategory = "INVALID_SECURITY"
        }
        fieldExceptions[] = {
        }
        fieldData[] = {
        }
    }
}
```

**Comment by matthewgilbert** [comment]
As of commit 240fd0fd747aa94fcba5ec80461b86748191ab98 you should now be able to use your code above to catch these types of errors, e.g.
```python
try:
    x = con.bdh('USBX@ Curncy', 'PX_BID', '20180509','20180509')
except ValueError:
    print("ERROR")

ERROR
```
