### ISSUE TITLE
Pricing Source override in BDH not working?

### ISSUE THREAD

**Issue by teoeme139** [matthewgilbert/pdblp#66]
Hi, Matt.

I have tried the following with many variations (i.e. PCS, PricingSource, pricingsource) and it doesn't seem to work. Any clues?

con = pdblp.BCon(timeout=5000)
con.start()
df = con.bdh(tickers=['AY24 Govt','AA21 Govt'], flds='PX_LAST', start_date='20190809', end_date='20190815',ovrds=[('PCS','BFUS')])
print(df)

I suspect the problem is in the ovrds field because when I run it without it, it works smoothly.

The error I get is:

Traceback (most recent call last):
  File "c:/Users/tollobet/AppData/Local/Programs/Python/Python37/Scripts/Py/Argentina/AY24-AA21.py", line 14, in <module>
    df = con.bdh(tickers=['AY24 Govt','AA21 Govt'], flds='PX_LAST', start_date='20190809', end_date='20190815',ovrds=[('PCS','BFUS')])
  File "C:\Users\tollobet\AppData\Local\Programs\Python\Python37\lib\site-packages\pdblp\pdblp.py", line 275, in bdh
    elms, ovrds)
  File "C:\Users\tollobet\AppData\Local\Programs\Python\Python37\lib\site-packages\pdblp\pdblp.py", line 307, in _bdh_list
    has_security_error = 'securityError' in d['securityData']
KeyError: 'securityData'

Thanks

**Comment by matthewgilbert** [comment]
It's helpful in theses cases to set `debug=True` in your connection object, i.e. `con.debug=True`, which lets you see the actual unparsed responses from Bloomberg. In your case this yields

```
pdblp.pdblp:INFO:Sending Request:
HistoricalDataRequest = {
    securities[] = {
        "AY24 Govt", "AA21 Govt"
    }
    fields[] = {
        "PX_LAST"
    }
    startDate = "20190809"
    endDate = "20190815"
    overrides[] = {
        overrides = {
            fieldId = "PCS"
            value = "BFUS"
        }
    }
}

pdblp.pdblp:INFO:Event Type: 'RESPONSE'
pdblp.pdblp:INFO:Message Received:
HistoricalDataResponse = {
    responseError = {
        source = "bbdbh6"
        code = 27
        category = "BAD_ARGS"
        message = "Invalid override field id specified [nid:194] "
        subcategory = "INVALID_OVERRIDE_FIELD"
    }
}
```

So it appears that this override is not valid. I would either looks at FLDS in the terminal to try and find what the appropriate override is or discuss with the help desk since this is Bloomberg `blpapi` specific.

**Comment by teoeme139** [comment]
Ok .Thank you. Bloomberg Support weren't very helpful.

BLOOMBERG HELP DESK : Unfortunately the Help Desk doesn't provide syntax support or creation for blpapi.

I don't see any overrides in FLDS, but the way I tried is how Excel manages it. I thought it would work as well. Well, thank you for your time. I'll post a solution later if I come up with one.

**Comment by matthewgilbert** [comment]
Yes the issue is the backend for the python API and Excel are not the same, so the FLDS uses in overrides are not identifcal to those in Excel. Possibly what you are looking for is `PRICING_SOURCE`.

![flds](https://user-images.githubusercontent.com/2401026/63207931-cde4de80-c100-11e9-8cdd-40a120e7da8b.jpg)

**Comment by teoeme139** [comment]
So, this didn't work. Although no error arises, the change in pricing source seems to make no difference. I found a way to make it work in FLDS but I'm not sure how to replicate it in pdblp.
The Pricing Source needs to be overwritten prior to calling the BDH function.
![imagen](https://user-images.githubusercontent.com/54152644/63274764-be87a180-c276-11e9-9f04-372df7ec9019.png)
And then I can see the PX_LAST I want to:
![imagen](https://user-images.githubusercontent.com/54152644/63274804-d2cb9e80-c276-11e9-8906-a9148bcf51ba.png)

Compare that with the default BVAL pricing source:
![imagen](https://user-images.githubusercontent.com/54152644/63274867-ed057c80-c276-11e9-9811-694f8370eb6b.png)
And:
![imagen](https://user-images.githubusercontent.com/54152644/63274904-fd1d5c00-c276-11e9-87f6-93f4b505a1ba.png)

Can you think of a way of doing this? I read the tutorial and saw no BDP function. Can this be called under the pdblp module?
Thanks

**Comment by matthewgilbert** [comment]
The override being ignored is a feature / antifeature of the underlying blpapi Bloomberg API. If you set an override value which is not applicable (the actual value not the override field) then it just ignores the override. For something similar to BDP take a look at `pdblp.BCon.ref`, which provides reference data.

**Comment by teoeme139** [comment]
Are you saying that 'BFUS' is not valid or that 'PRICING_SOURCE' is not valid for 'PX_LAST'? I know for certain that 'BFUS' is a valid source. I'll see if I can find a workaround with the second function.

**Comment by teoeme139** [comment]
Best solution so far is to change the values in the terminal PCS menu. This forces you to use the same pricing source for all securities, but it's a start.

**Comment by matthewgilbert** [comment]
I am saying that when you make a `HistoricalDataRequest`, setting `BFUS` for `PRICING_SOURCE` does not affect `PX_LAST`. For example

Historical request without override
```
HistoricalDataRequest = {
    securities[] = {
        "AY24 Govt"
    }
    fields[] = {
        "PX_LAST"
    }
    startDate = "20190815"
    endDate = "20190815"
    overrides[] = {
    }
}

HistoricalDataResponse = {
    securityData = {
        security = "AY24 Govt"
        eidData[] = {
        }
        sequenceNumber = 0
        fieldExceptions[] = {
        }
        fieldData[] = {
            fieldData = {
                date = 2019-08-15
                PX_LAST = 52.967000
            }
        }
    }
}
```
Historical data request with override
```
HistoricalDataRequest = {
    securities[] = {
        "AY24 Govt"
    }
    fields[] = {
        "PX_LAST"
    }
    startDate = "20190815"
    endDate = "20190815"
    overrides[] = {
        overrides = {
            fieldId = "PRICING_SOURCE"
            value = "BFUS"
        }
    }
}

HistoricalDataResponse = {
    securityData = {
        security = "AY24 Govt"
        eidData[] = {
        }
        sequenceNumber = 0
        fieldExceptions[] = {
        }
        fieldData[] = {
            fieldData = {
                date = 2019-08-15
                PX_LAST = 52.967000
            }
        }
    }
}
```
whereas it does seem to affect the pricing when you make a `ReferenceDataRequest`. I am unsure why this is.

Reference data without override
```
ReferenceDataRequest = {
    securities[] = {
        "AY24 Govt"
    }
    fields[] = {
        "PX_LAST"
    }
    overrides[] = {
    }
}

ReferenceDataResponse = {
    securityData[] = {
        securityData = {
            security = "AY24 Govt"
            eidData[] = {
            }
            fieldExceptions[] = {
            }
            sequenceNumber = 0
            fieldData = {
                PX_LAST = 46.076000
            }
        }
    }
}
```
Reference data with override
```
ReferenceDataRequest = {
    securities[] = {
        "AY24 Govt"
    }
    fields[] = {
        "PX_LAST"
    }
    overrides[] = {
        overrides = {
            fieldId = "PRICING_SOURCE"
            value = "BFUS"
        }
    }
}

ReferenceDataResponse = {
    securityData[] = {
        securityData = {
            security = "AY24 Govt"
            eidData[] = {
            }
            fieldExceptions[] = {
            }
            sequenceNumber = 0
            fieldData = {
                PX_LAST = 46.100000
            }
        }
    }
}
```

**Comment by jzabroski** [comment]
#### Why is it so confusing this is not working?
Worth noting that part of the confusion here appears to be the Bloomberg Developer portal documentation for the B-PIPE Historical API says:

https://developer.blpprofessional.com/portal/products/b_pipe?chapterId=5239&entityType=document#b_pipe-bbg_professional_user_services-data_for_bps_users-historical_data_requests-historical_eod_data_request_elements_and_options

<img width="2195" height="346" alt="Image" src="https://github.com/user-attachments/assets/42fec384-f603-4392-ac9a-f4d42f9f36a3" />

#### What to do?
The un-documented approach for setting the pricing source is to include the pricing source in the ticker. This approach is not great as the format for specifying the pricing source in the ticker is not documented (I maintain an in-house ticker parsing library in C#, and I am on about the 10th version of it, as I keep finding edge cases I did not previously consider) and the canonical format for the Bloomberg ParseKeyable Desc value has changed over time (e.g., date formats in tickers are now yyyy instead of just yy).

* For INDEX yellow key-suffixed tickers, PCS is invalid. You can verify this by going into Bloomberg Terminal and trying any INDEX security you use (e.g. SOFR INDEX) and adding " PCS" to the end of the ticker to bring up the PCS screen for that security.
* For CURNCY yellow key-suffixed tickers, the format is "`<currency ticker>` `<PCS>` CURNCY". So, if you want to specify BGN as your pricing source, KRW CURNCY becomes KRW BGN CURNCY.
* For EQUITY yellow key-suffixed tickers, the format is "`<EXCH_SYMBOL>`@`<PCS>` `<EXCH_CODE>` EQUITY". So, if you want to specify BGN as your pricing source, IBM US EQUITY becomes IBM@BGN US EQUITY.

**Comment by jzabroski** [comment]
> Best solution so far is to change the values in the terminal PCS menu.
> -- @truebrew 

How do you do that for BPIPE, if your BPIPE is authenticated under an application name? Worth noting the default is REGN (Regional BGN).

**Comment by jzabroski** [comment]
As a follow up here, discussed with Bloomberg.

1. When viewing PX_LAST in FLDS, the Override checkbox is not available, which means it does not support a list of "Reacts To" field/value pairs. When a field does support "Reacts To", the Override checkbox is available, and if you click on the field in FLDS, the description screen has a radio button that says "Reacts To". If you click it, you will see the full list of field/value pairs you can pass in via BLPAPI.
2. When requesting PX_LAST over historical requests, you cannot return PRICING_SOURCE, PRICING_SOURCE_RT or FEED_SOURCE_BPIPE_REALTIME. Ergo, there is no way to actually know what pricing source generated the price you get back from PX_LAST.
    a. Maybe if enough people read this and mention it to Bloomberg, they will address, but for now, the ONLY way to GUARANTEE you know what your pricing source is to use the PCS in the BloombergParseKey ("ticker") in the request.
3. I am adamant it is a bug that BPIPE defaults to Regional BGN for FX Rates/Government Yields.
